name: projetoacademia
description: "Aplicação para Controle de Exercícios Físicos."

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.1
  location: ^6.0.2
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_switch: ^0.3.2
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0

  fluttertoast: ^8.2.5



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 34


flutter:


  uses-material-design: true

  assets:
    - assets/




