// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3b7f_1cyxv4bEW96dNeFWJMhKh0mqPiw',
    appId: '1:921348313705:web:756a44419085fb16a248f8',
    messagingSenderId: '921348313705',
    projectId: 'proj-flutter-restapi',
    authDomain: 'proj-flutter-restapi.firebaseapp.com',
    storageBucket: 'proj-flutter-restapi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9eL_XL-ZOjy7TPFP66w8L3ztQaBZeKZQ',
    appId: '1:921348313705:android:35c08d41f7d9d861a248f8',
    messagingSenderId: '921348313705',
    projectId: 'proj-flutter-restapi',
    storageBucket: 'proj-flutter-restapi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNN20VsNQOBwiLP_3yqrAgAIAKid5HdKU',
    appId: '1:921348313705:ios:1f449c0a410cb0aca248f8',
    messagingSenderId: '921348313705',
    projectId: 'proj-flutter-restapi',
    storageBucket: 'proj-flutter-restapi.appspot.com',
    iosClientId: '921348313705-0i0k5vt6hjqlobteitmul8uldam2sucv.apps.googleusercontent.com',
    iosBundleId: 'br.edu.infnet.projetoacademia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3b7f_1cyxv4bEW96dNeFWJMhKh0mqPiw',
    appId: '1:921348313705:web:831896f436ef0119a248f8',
    messagingSenderId: '921348313705',
    projectId: 'proj-flutter-restapi',
    authDomain: 'proj-flutter-restapi.firebaseapp.com',
    storageBucket: 'proj-flutter-restapi.appspot.com',
  );
}
